### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by Mahesh1** [holochain/happ-build-tutorial#17]
Hi I am trying out my first holochain app. i am using BigSur v11.4.
i made no change to the code. 
On step 5: Testing when i run `npm test` it fails. Here is the output

[nix-shell:~/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests]$ npm test

> demo-1@0.0.0 test /Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests
> TRYORAMA_LOG_LEVEL=info RUST_LOG=error RUST_BACKTRACE=1 TRYORAMA_HOLOCHAIN_PATH="holochain" ts-node src/index.ts

13:47:49 [tryorama] info: Using the following settings from environment variables:
13:47:49 [tryorama] info: {
  "adminInterfaceId": "tryorama-interface-admin",
  "appInterfaceId": "tryorama-interface-app",
  "stateDumpOnError": true,
  "zomeCallTimeoutMs": 90000,
  "conductorTimeoutMs": 125000,
  "strictConductorTimeout": false,
  "chooseFreePort": false,
  "logLevel": "info",
  "portRange": [
    33000,
    34000
  ],
  "legacy": false,
  "singletonAppId": "TRYORAMA_APP",
  "holochainPath": "holochain",
  "lairPath": "lair-keystore"
}
TAP version 13
# sample test
FIXME: ignoring onJoin
13:47:49 [tryorama] info: Spawning lair for test with keystore at:  /tmp/tmp.hGwlsptwYe/tryorama/iLroj2/keystore
13:47:50 [tryorama] info: Using conductor path:  holochain
13:47:50 [tryorama] info: Holochain version:     holochain 0.0.100

13:47:50 [tryorama] info: Conductor config path: /tmp/tmp.hGwlsptwYe/tryorama/iLroj2/conductor-config.yml
13:47:50 info:
☉☉☉ [[[CONDUCTOR c0]]]
☉
☉ ###HOLOCHAIN_SETUP###
☉ ###ADMIN_PORT:33000###
☉ ###HOLOCHAIN_SETUP_END###
☉ Conductor ready.
☉
13:47:50 [tryorama] info: Conductor 'c0' process spawning completed.
App Port spun up on port  61687
13:47:51 info:
★★★ {{{CONDUCTOR c0}}}
★ FATAL PANIC PanicInfo {
★     payload: Any,
★
13:47:51 info:
☯☯☯ {{{CONDUCTOR c0}}}
☯     message: Some(
☯         TODO: ZomeError(ZomeNotFound("Zome \'numbers\' not found")),
☯     ),
☯     location: Location {
☯         file: "/private/tmp/nix-build-holochain.drv-0/source/crates/holochain/src/core/ribosome.rs",
☯         line: 339,
☯         col: 14,
☯     },
☯ }
☯ thread 'holochain-tokio-thread' panicked at 'TODO: ZomeError(ZomeNotFound("Zome \'numbers\' not found"))', /private/tmp/nix-build-holochain.drv-0/source/crates/holochain/src/core/ribosome.rs:339:14
☯ stack backtrace:
☯
13:47:51 info:
☸☸☸ {{{CONDUCTOR c0}}}
☸ note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
☸
13:48:21 [tryorama] error: Test error: 'Error: Timed out in 30000ms: zome_call_invocation\n' +
  '    at Timeout.<anonymous> (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/@holochain/conductor-api/src/websocket/common.ts:16:14)\n' +
  '    at listOnTimeout (internal/timers.js:554:17)\n' +
  '    at processTimers (internal/timers.js:497:7)'
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:91:32)
          at Test.fail (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:398:10)
          at Test.bound [as fail] (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:91:32)
          at /Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13
  ...
13:49:55 [tryorama] error:
The following conductors were forcefully shutdown after 125 seconds of no activity:

^C

**Comment by Connoropolous** [comment]
I just noticed someone on the forum had a similar or the same issue. I will try today myself to reproduce and if I can, fix this.

**Comment by Connoropolous** [comment]
@Mahesh1 did you run steps 1 to 4 immediately before running step 5? 

Did you run
`CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown`
for example?

**Comment by Connoropolous** [comment]
I just went through it fresh myself, and it worked fine.

**Comment by benoitfrontzak** [comment]
same happened to me too.

I tried to go straight to step 5
I tried another time following all steps (Issue on step 3 with path...Had to move the folder target to dna-folder)

Both ways ends with error message :

`thread 'holochain-tokio-thread' panicked at 'TODO: ZomeError(ZomeNotFound("Zome \'numbers\' not found"))', /tmp/nix-build-holochain.drv-1/source/crates/holochain/src/core/ribosome.rs:339:14`

**Comment by Connoropolous** [comment]
I'm having trouble figuring out what's wrong. I can't reproduce it myself, so I'm going to need somebody's further assistance. 

@benoitfrontzak can you clarify this?
"I tried another time following all steps (Issue on step 3 with path...Had to move the folder target to dna-folder)"
what was the exact issue that occurred? can you paste in  terminal output from that ? 

I know that it's not just me who it's working for because the continuous integration test runner has its tests passing, which test the same thing as the instructions say to do. Can you confirm you ran these steps in this order? 
<img width="849" alt="Screen Shot 2021-07-31 at 8 17 05 AM" src="https://user-images.githubusercontent.com/1409121/127744474-f2fae338-a204-4da0-890d-b74314ec5cc1.png">

**Comment by Mahesh1** [comment]
> @Mahesh1 did you run steps 1 to 4 immediately before running step 5?
> 
> Did you run
> `CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown`
> for example?

Hi @Connoropolous yes i ran that cmd. i followed the tutorial & all the steps 1-4, till 5 when i got the error

**Comment by Connoropolous** [comment]
Hi @Mahesh1 thanks. Can you confirm that your workdir/dna/dna.yaml file looks like this? 

```yaml
---
manifest_version: "1"
name: demo-dna
uuid: ~
properties: ~
zomes: 
  - name: numbers
    bundled: ../../target/wasm32-unknown-unknown/release/numbers.wasm
  - name: whoami
    bundled: ../../target/wasm32-unknown-unknown/release/whoami.wasm
```

can you also confirm that you have a file at this path? like seen in my screenshot
`target/wasm32-unknown-unknown/release/numbers.wasm`
<img width="316" alt="Screen Shot 2021-07-31 at 8 27 24 AM" src="https://user-images.githubusercontent.com/1409121/127744693-ac8217ca-d6c3-4cee-8903-c409b181f292.png">

**Comment by Mahesh1** [comment]
Hi @Connoropolous first off, thank you for looking into this. here's the screen shot confirming
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1794702/127744823-f8fcb1c7-fa91-42f3-ba1a-3295ab5434b9.png">

**Comment by Connoropolous** [comment]
You're welcome. Now those things look good. 

Did you have any issue with step 3 like benoit?

**Comment by Mahesh1** [comment]
Hi @Connoropolous , 
I definitely ran step 2 to build the wasm file, but Its possible i might have skipped step 3,4 as the .dna file is there in the workdir resp folders. 
i will try again the tutorial. will let you know.

**Comment by Connoropolous** [comment]
oooooo. that will be it

**Comment by Connoropolous** [comment]
all you would need in particular is to run: 

`hc dna pack workdir/dna`
and then 
`cd tests`
and then
`npm test`

**Comment by Connoropolous** [comment]
I updated the included dna files so they will work too, if someone else does what you did

**Comment by Mahesh1** [comment]
Thank you so much, will try it and update you, later today

**Comment by Mahesh1** [comment]
> all you would need in particular is to run:
> 
> `hc dna pack workdir/dna`
> and then
> `cd tests`
> and then
> `npm test`

Hi @Connoropolous, i ran step 3,4,5 but got an error. not sure if i was supposed to run step 4. 

[nix-shell:~/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests]$ npm test

> demo-1@0.0.0 test /Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests
> TRYORAMA_LOG_LEVEL=info RUST_LOG=error RUST_BACKTRACE=1 TRYORAMA_HOLOCHAIN_PATH="holochain" ts-node src/index.ts

13:06:43 [tryorama] info: Using the following settings from environment variables:
13:06:43 [tryorama] info: {
  "adminInterfaceId": "tryorama-interface-admin",
  "appInterfaceId": "tryorama-interface-app",
  "stateDumpOnError": true,
  "zomeCallTimeoutMs": 90000,
  "conductorTimeoutMs": 125000,
  "strictConductorTimeout": false,
  "chooseFreePort": false,
  "logLevel": "info",
  "portRange": [
    33000,
    34000
  ],
  "legacy": false,
  "singletonAppId": "TRYORAMA_APP",
  "holochainPath": "holochain",
  "lairPath": "lair-keystore"
}
TAP version 13
# sample test
FIXME: ignoring onJoin
13:06:43 [tryorama] info: Spawning lair for test with keystore at:  /tmp/tmp.uSkSzGWG8l/tryorama/h8csc3/keystore
13:06:43 [tryorama] info: Using conductor path:  holochain
13:06:43 [tryorama] info: Holochain version:     holochain 0.0.100

13:06:43 [tryorama] info: Conductor config path: /tmp/tmp.uSkSzGWG8l/tryorama/h8csc3/conductor-config.yml
13:06:43 info:
☉☉☉ [[[CONDUCTOR c0]]]
☉
☉ ###HOLOCHAIN_SETUP###
☉ ###ADMIN_PORT:33000###
☉ ###HOLOCHAIN_SETUP_END###
☉ Conductor ready.
☉
13:06:43 [tryorama] info: Conductor 'c0' process spawning completed.
App Port spun up on port  52999
13:06:43 [tryorama] error: Test error: {
  type: 'error',
  data: {
    type: 'ribosome_error',
    data: 'Wasm error while working with Ribosome: Compile("Error while importing \\"env\\".\\"__import_data\\": incompatible import type. Expected Function(FunctionType { params: [I32], results: [] }) but received Function(FunctionType { params: [], results: [I64] })")'
  }
}
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:91:32)
          at Test.fail (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:398:10)
          at Test.bound [as fail] (/Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/tape/lib/test.js:91:32)
          at /Users/mahesh/mycode/holochain/holotutorials/firsthapp/happ-build-tutorial/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...
13:06:43 [tryorama] info: conductor 'c0' exited with code null
FIXME: ignoring onLeave

1..1
# tests 1
# pass  0
# fail  1

npm ERR! Test failed.  See above for more details.

**Comment by Mahesh1** [comment]
Ran all the steps but I still have the new error. i also ran `hc sanbox clean` & then tried `npm test` again, but still getting the error

**Comment by Connoropolous** [comment]
Ok well its a different error :s thats progress I think hah

**Comment by benoitfrontzak** [comment]
Hi guys

Sorry I didn't realize the conversation...I thought it will be notification
from the Forum and I was following it...
Anyway, I reproduce step by step the process and this time I success...
For reproduce error with the folder...check the attache doc

Thanks guys

**Comment by Connoropolous** [comment]
yay!
